export const CustomersData = {
	customers: [
		{
			id: 1,
			name: "Customer 1",
			title: "Mr.",
			address: {
				street: "123 Main St",
				city: "City 1",
				state: "State 1",
				postalCode: "10001",
				country: "USA",
			},
		},
		{
			id: 2,
			name: "Customer 2",
			title: "Ms.",
			address: {
				street: "124 Main St",
				city: "City 2",
				state: "State 2",
				postalCode: "10002",
				country: "USA",
			},
		},
		{
			id: 3,
			name: "Customer 3",
			title: "Dr.",
			address: {
				street: "125 Main St",
				city: "City 3",
				state: "State 3",
				postalCode: "10003",
				country: "USA",
			},
		},
		{
			id: 4,
			name: "Customer 4",
			title: "Mr.",
			address: {
				street: "126 Main St",
				city: "City 4",
				state: "State 4",
				postalCode: "10004",
				country: "USA",
			},
		},
		{
			id: 5,
			name: "Customer 5",
			title: "Ms.",
			address: {
				street: "127 Main St",
				city: "City 5",
				state: "State 5",
				postalCode: "10005",
				country: "USA",
			},
		},
		{
			id: 6,
			name: "Customer 6",
			title: "Dr.",
			address: {
				street: "128 Main St",
				city: "City 6",
				state: "State 6",
				postalCode: "10006",
				country: "USA",
			},
		},
		{
			id: 7,
			name: "Customer 7",
			title: "Mr.",
			address: {
				street: "129 Main St",
				city: "City 7",
				state: "state 7",
				postalCode: "10007",
				country: "USA",
			},
		},
		{
			id: 8,
			name: "Customer 8",
			title: "Ms.",
			address: {
				street: "130 Main St",
				city: "City 8",
				state: "State 8",
				postalCode: "10008",
				country: "USA",
			},
		},
		{
			id: 9,
			name: "Customer 9",
			title: "Dr.",
			address: {
				street: "131 Main St",
				city: "City 9",
				state: "State 9",
				postalCode: "10009",
				country: "USA",
			},
		},
		{
			id: 10,
			name: "Customer 10",
			title: "Mr.",
			address: {
				street: "132 Main St",
				city: "City 10",
				state: "State 10",
				postalCode: "10010",
				country: "USA",
			},
		},
		{
			id: 11,
			name: "Customer 11",
			title: "Ms.",
			address: {
				street: "133 Main St",
				city: "City 11",
				state: "State 11",
				postalCode: "10011",
				country: "USA",
			},
		},
		{
			id: 12,
			name: "Customer 12",
			title: "Dr.",
			address: {
				street: "134 Main St",
				city: "City 12",
				state: "State 12",
				postalCode: "10012",
				country: "USA",
			},
		},
		{
			id: 13,
			name: "Customer 13",
			title: "Mr.",
			address: {
				street: "135 Main St",
				city: "City 13",
				state: "State 13",
				postalCode: "10013",
				country: "USA",
			},
		},
		{
			id: 14,
			name: "Customer 14",
			title: "Ms.",
			address: {
				street: "136 Main St",
				city: "City 14",
				state: "State 14",
				postalCode: "10014",
				country: "USA",
			},
		},
		{
			id: 15,
			name: "Customer 15",
			title: "Dr.",
			address: {
				street: "137 Main St",
				city: "City 15",
				state: "State 15",
				postalCode: "10015",
				country: "USA",
			},
		},
		{
			id: 16,
			name: "Customer 16",
			title: "Mr.",
			address: {
				street: "138 Main St",
				city: "City 16",
				state: "State 16",
				postalCode: "10016",
				country: "USA",
			},
		},
		{
			id: 17,
			name: "Customer 17",
			title: "Ms.",
			address: {
				street: "139 Main St",
				city: "City 17",
				state: "State 17",
				postalCode: "10017",
				country: "USA",
			},
		},
		{
			id: 18,
			name: "Customer 18",
			title: "Dr.",
			address: {
				street: "140 Main St",
				city: "City 18",
				state: "State 18",
				postalCode: "10018",
				country: "USA",
			},
		},
		{
			id: 19,
			name: "Customer 19",
			title: "Mr.",
			address: {
				street: "141 Main St",
				city: "City 19",
				state: "State 19",
				postalCode: "10019",
				country: "USA",
			},
		},
		{
			id: 20,
			name: "Customer 20",
			title: "Ms.",
			address: {
				street: "142 Main St",
				city: "City 20",
				state: "State 20",
				postalCode: "10020",
				country: "USA",
			},
		},
		{
			id: 21,
			name: "Customer 21",
			title: "Dr.",
			address: {
				street: "143 Main St",
				city: "City 21",
				state: "State 21",
				postalCode: "10021",
				country: "USA",
			},
		},
		{
			id: 22,
			name: "Customer 22",
			title: "Mr.",
			address: {
				street: "144 Main St",
				city: "City 22",
				state: "State 22",
				postalCode: "10022",
				country: "USA",
			},
		},
		{
			id: 23,
			name: "Customer 23",
			title: "Ms.",
			address: {
				street: "145 Main St",
				city: "City 23",
				state: "State 23",
				postalCode: "10023",
				country: "USA",
			},
		},
		{
			id: 24,
			name: "Customer 24",
			title: "Dr.",
			address: {
				street: "146 Main St",
				city: "City 24",
				state: "State 24",
				postalCode: "10024",
				country: "USA",
			},
		},
		{
			id: 25,
			name: "Customer 25",
			title: "Mr.",
			address: {
				street: "147 Main St",
				city: "City 25",
				state: "State 25",
				postalCode: "10025",
				country: "USA",
			},
		},
		{
			id: 26,
			name: "Customer 26",
			title: "Ms.",
			address: {
				street: "148 Main St",
				city: "City 26",
				state: "State 26",
				postalCode: "10026",
				country: "USA",
			},
		},
		{
			id: 27,
			name: "Customer 27",
			title: "Dr.",
			address: {
				street: "149 Main St",
				city: "City 27",
				state: "State 27",
				postalCode: "10027",
				country: "USA",
			},
		},
		{
			id: 28,
			name: "Customer 28",
			title: "Mr.",
			address: {
				street: "150 Main St",
				city: "City 28",
				state: "State 28",
				postalCode: "10028",
				country: "USA",
			},
		},
		{
			id: 29,
			name: "Customer 29",
			title: "Ms.",
			address: {
				street: "151 Main St",
				city: "City 29",
				state: "State 29",
				postalCode: "10029",
				country: "USA",
			},
		},
		{
			id: 30,
			name: "Customer 30",
			title: "Dr.",
			address: {
				street: "152 Main St",
				city: "City 30",
				state: "State 30",
				postalCode: "10030",
				country: "USA",
			},
		},
		{
			id: 31,
			name: "Customer 31",
			title: "Mr.",
			address: {
				street: "153 Main St",
				city: "City 31",
				state: "State 31",
				postalCode: "10031",
				country: "USA",
			},
		},
		{
			id: 32,
			name: "Customer 32",
			title: "Ms.",
			address: {
				street: "154 Main St",
				city: "City 32",
				state: "State 32",
				postalCode: "10032",
				country: "USA",
			},
		},
		{
			id: 33,
			name: "Customer 33",
			title: "Dr.",
			address: {
				street: "155 Main St",
				city: "City 33",
				state: "State 33",
				postalCode: "10033",
				country: "USA",
			},
		},
		{
			id: 34,
			name: "Customer 34",
			title: "Mr.",
			address: {
				street: "156 Main St",
				city: "City 34",
				state: "State 34",
				postalCode: "10034",
				country: "USA",
			},
		},
	],
};
